const SET_EMAIL = "SET_EMAIL";
const SET_PASSWORD = "SET_PASSWORD";
const SET_CONFIRM = "SET_CONFIRM";
const ACCOUNT_CHANGED_RENDER = "ACCOUNT_CHANGED_RENDER";
const EDIT_ACCOUNT = "EDIT_ACCOUNT";
const LOGGED_IN_USER = "LOGGED_IN_USER";

export {
  SET_EMAIL,
  SET_PASSWORD,
  SET_CONFIRM,
  ACCOUNT_CHANGED_RENDER,
  EDIT_ACCOUNT,
  LOGGED_IN_USER,
};
